config/routes.rb
Vic::Application.routes.draw do
  resources :mdm_tugboats

  resources :vessel_inventories

  root :to => 'vessel_inventories#index'

end

app/models/mdm_tugboat.rb
class MdmTugboat < ActiveRecord::Base
  has_many :vessel_inventories, :dependent => :destroy
end

app/models/vessel_inventory.rb
class VesselInventory < ActiveRecord::Base
	attr_accessible :mdm_tugboat_id, :location, :parts_name, :interval_period, :interval_period_unit, 
		:interval_period_changeable, :position, :last_change_record_period, :last_change_record_date, 
		:last_change_record_executor, :current_hours, :next_change_date, :next_change_hours

	belongs_to :mdm_tugboat

	def self.special_save(value, boat_id, position)
    vi = VesselInventory.new(value)
    vi.mdm_tugboat_id = boat_id
    vi.position = position
    vi.interval_period_changeable = false if vi.interval_period_unit == 'Months'
    vi.save
	end

	def params_calculation(par)
    if par[:last_change_record_date]
      if par[:interval_period_unit] == 'Hours'
        par[:next_change_hours] = self.interval_period + par[:last_change_record_period].to_i - par[:current_hours].to_i
        par[:next_change_date] = par[:last_change_record_date].to_date + (par[:next_change_hours].to_i / 24).days
      else
        par[:next_change_date] = par[:last_change_record_date].to_date + self.interval_period.months
      end
    end
    nil
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mdm_tugboats_controller.rb
class MdmTugboatsController < ApplicationController
  # GET /mdm_tugboats
  # GET /mdm_tugboats.json
  def index
    @mdm_tugboats = MdmTugboat.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mdm_tugboats }
    end
  end

  # GET /mdm_tugboats/1
  # GET /mdm_tugboats/1.json
  def show
    @mdm_tugboat = MdmTugboat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mdm_tugboat }
    end
  end

  # GET /mdm_tugboats/new
  # GET /mdm_tugboats/new.json
  def new
    @mdm_tugboat = MdmTugboat.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mdm_tugboat }
    end
  end

  # GET /mdm_tugboats/1/edit
  def edit
    @mdm_tugboat = MdmTugboat.find(params[:id])
  end

  # POST /mdm_tugboats
  # POST /mdm_tugboats.json
  def create
    @mdm_tugboat = MdmTugboat.new(params[:mdm_tugboat])

    respond_to do |format|
      if @mdm_tugboat.save
        format.html { redirect_to @mdm_tugboat, notice: 'Mdm tugboat was successfully created.' }
        format.json { render json: @mdm_tugboat, status: :created, location: @mdm_tugboat }
      else
        format.html { render action: "new" }
        format.json { render json: @mdm_tugboat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mdm_tugboats/1
  # PUT /mdm_tugboats/1.json
  def update
    @mdm_tugboat = MdmTugboat.find(params[:id])

    respond_to do |format|
      if @mdm_tugboat.update_attributes(params[:mdm_tugboat])
        format.html { redirect_to @mdm_tugboat, notice: 'Mdm tugboat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mdm_tugboat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mdm_tugboats/1
  # DELETE /mdm_tugboats/1.json
  def destroy
    @mdm_tugboat = MdmTugboat.find(params[:id])
    @mdm_tugboat.destroy

    respond_to do |format|
      format.html { redirect_to mdm_tugboats_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/vessel_inventories_controller.rb
class VesselInventoriesController < ApplicationController
  # GET /vessel_inventories
  # GET /vessel_inventories.json
  def index
    @vessel_inventories = {}
    # VesselInventory.order('created_at').all(:include => :mdm_tugboat)
    # tug_ids = @vessel_inventories.map{|x| x.mdm_tugboat_id}.uniq
    @tugboats = MdmTugboat.order('name').includes(:vessel_inventories).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vessel_inventories }
    end
  end

  # GET /vessel_inventories/1
  # GET /vessel_inventories/1.json
  def show
    @vessel_inventory = VesselInventory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vessel_inventory }
    end
  end

  # GET /vessel_inventories/new
  # GET /vessel_inventories/new.json
  def new
    @vessel_inventory = VesselInventory.new
    @tugboats = MdmTugboat.order('name').all
    @values = {}
    @values['MAIN ENGINE'] = ['FUEL INJECTION PUMP', 'INJECTOR NOZZLE', 'FO FILTER', 'LO FILTER', 'LUB OIL', 'BATTERY']
    @values['GENERATOR'] = ['INJECTOR NOZZLE', 'FO FILTER', 'LO FILTER', 'BATTERY']
    @values['DECK'] = ['RADAR', 'GPS', 'BATTERY', 'LIFE JACKET', 'LIFE BUOY', 'SEARCH LIGHT', 'MOORING ROPE', 'TOWING SHACKLESS', 'TOWING WIRE', 'TOWING ROPE']

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vessel_inventory }
    end
  end

  # GET /vessel_inventories/1/edit
  def edit
    @vessel_inventory = VesselInventory.find(params[:id], :include => :mdm_tugboat)
  end

  # POST /vessel_inventories
  # POST /vessel_inventories.json
  def create
    params[:vic].each do |key, value|
      if params[:amount][key] == '1'
        VesselInventory.special_save(value, params[:boat_id], 'PORT')
        VesselInventory.special_save(value, params[:boat_id], 'STBD')
      else
        if params[:amount][key].blank?
          VesselInventory.special_save(value, params[:boat_id], nil)
        else
          params[:amount][key].to_i.times {|num| VesselInventory.special_save(value, params[:boat_id], 'PORT #'+(num+1).to_s)}
          params[:amount][key].to_i.times {|num| VesselInventory.special_save(value, params[:boat_id], 'STBD #'+(num+1).to_s)}
        end
      end
    end

    redirect_to :action => 'index', notice: 'Vessel inventory was successfully created.'
    # @vessel_inventory = VesselInventory.new(params[:vessel_inventory])

    # respond_to do |format|
    #   if @vessel_inventory.save
    #     format.html { redirect_to @vessel_inventory, notice: 'Vessel inventory was successfully created.' }
    #     format.json { render json: @vessel_inventory, status: :created, location: @vessel_inventory }
    #   else
    #     format.html { render action: "new" }
    #     format.json { render json: @vessel_inventory.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PUT /vessel_inventories/1
  # PUT /vessel_inventories/1.json
  def update
    @vessel_inventory = VesselInventory.find(params[:id])
    @vessel_inventory.params_calculation(params[:vessel_inventory])
# binding.pry
    respond_to do |format|
      if @vessel_inventory.update_attributes(params[:vessel_inventory])
        format.html { redirect_to vessel_inventories_url, notice: 'Vessel inventory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vessel_inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vessel_inventories/1
  # DELETE /vessel_inventories/1.json
  def destroy
    @vessel_inventory = VesselInventory.find(params[:id])
    @vessel_inventory.destroy

    respond_to do |format|
      format.html { redirect_to vessel_inventories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_toggle(menu)
    if menu == 'master'
      'active' if ['mdm_tugboats'].include?(params[:controller])
    else
      'active' if menu == params[:controller]
    end
  end
end

app/helpers/mdm_tugboats_helper.rb
module MdmTugboatsHelper
end

app/helpers/vessel_inventories_helper.rb
module VesselInventoriesHelper
  def hours_months_print(str1, str2)
    '<option value="'+str1+'">'+str1+'</option><option value="'+str2+'">'+str2+'</option>'
  end

  def hours_or_months(iteration, location)
    data = location == 'DECK' ? hours_months_print('Months', 'Hours').html_safe : hours_months_print('Hours', 'Months').html_safe
    select_tag 'vic['+iteration.to_s+'][interval_period_unit]', data, :class => 'text_field'
  end

  def row_style(ncd)
    if ncd
      range = (ncd - Time.now.to_date).to_i
      if range < 0
        'class=vic-danger'
      else
        if range < 40
          'class=vic-alert'
        else
          ''
        end
      end
    else
      ''
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "VIC" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <!-- <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script> -->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

<!-- Latest compiled and minified CSS -->
<!-- <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css"> -->

<!-- Optional theme -->
<!-- <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css"> -->

<!-- Latest compiled and minified JavaScript -->
<!-- <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script> -->

    <script type="text/javascript">
    $(function (){
      $('#vessel_inventory_last_change_record_date').datepicker({ dateFormat: "yy-mm-dd" });
    });
    </script>
    <style type="text/css">
    .vic-alert {background: #ffff00;}
    .vic-danger {background: #ff0000; color: #ffffff;}
    </style>
  </head>
  <body>

    <div class="navbar navbar-fluid-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to image_tag("header-logo.png", :style => 'height: 50px'), root_path, :class => "brand" %>
          <h5 class="navbar-text">Vessel Inventory Control</h5>
          <!-- <a class="brand" href="#">Vic</a> -->
          <div class="container-fluid nav-collapse">
<!--         <div class="navbar-collapse collapse">

        </div> -->
            <ul class="nav navbar-nav">
              <li class='<%= active_toggle('vessel_inventories') %>'><%= link_to 'Dashboard', root_path %></li>
              <li><%= link_to 'Tugboat', mdm_tugboats_path %></li>
              <li class="dropdown <%= active_toggle('master') %>">
                <a class="dropdown-toggle" data-toggle="dropdown">Master Data <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Tugboat', mdm_tugboats_path %></li>
                </ul>
              </li>
            </ul>
          </div>
          <!--/.nav-collapse -->
        </div>

      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="container">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; PT. Trust Line Marine, IT Division 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/mdm_tugboats/_form.html.erb
<%= form_for @mdm_tugboat, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @mdm_tugboat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mdm_tugboat.errors.count, "error") %> prohibited this mdm_tugboat from being saved:</h2>

      <ul>
      <% @mdm_tugboat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :code, :class => "text-field" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => "text-field" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :std_consm_empty, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :std_consm_empty, :class => "text-field" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :std_consm_loaded, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :std_consm_loaded, :class => "text-field" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :std_consm_idle, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :std_consm_idle, :class => "text-field" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :std_speed_empty, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :std_speed_empty, :class => "text-field" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :std_speed_loaded, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :std_speed_loaded, :class => "text-field" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => "text-area" %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to "Cancel", mdm_tugboats_path, :class => 'btn' %>
  </div>
<% end %>

app/views/mdm_tugboats/edit.html.erb
<h1>Editing mdm_tugboat</h1>

<%= render 'form' %>

app/views/mdm_tugboats/index.html.erb
<div class="page-header">
  <%= link_to 'New Tugboat', new_mdm_tugboat_path, :class => 'btn btn-primary pull-right' %>
  <h1>Listing Tugboat</h1>
</div>

<table class="table table-condensed table-bordered table-hover table-striped">
  <thead>
    <tr style="background-color: #428bca; color: #ffffff;">
      <th>Code</th>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @mdm_tugboats.each do |mdm_tugboat| %>
    <tr>
      <td><%= mdm_tugboat.code %></td>
      <td><%= mdm_tugboat.name %></td>
      <td>
        <%= link_to 'Show', mdm_tugboat, :class => 'btn btn-mini btn-info' %>
        <%= link_to 'Edit', edit_mdm_tugboat_path(mdm_tugboat), :class => 'btn btn-mini btn-warning' %>
        <%= link_to 'Destroy', mdm_tugboat, confirm: 'Are you sure?', method: :delete, :class => 'btn btn-mini btn-danger' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/mdm_tugboats/new.html.erb
<h1>New Tugboat</h1>

<%= render 'form' %>

app/views/mdm_tugboats/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_mdm_tugboat_path(@mdm_tugboat) %> |
<%= link_to 'Back', mdm_tugboats_path %>

app/views/vessel_inventories/_form.html.erb
<%= form_for @vessel_inventory, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= label_tag nil, 'Tugboat', :class => 'control-label' %>
    <div class="controls">
      <%= text_field_tag nil, @vessel_inventory.mdm_tugboat.name, :class => 'number_field', :disabled => true %>
    </div>
  </div>
  <div class="control-group">
    <%= label_tag nil, 'Location', :class => 'control-label' %>
    <div class="controls">
      <%= text_field_tag nil, @vessel_inventory.location, :class => 'number_field', :disabled => true %>
    </div>
  </div>
  <div class="control-group">
    <%= label_tag nil, 'Parts Name', :class => 'control-label' %>
    <div class="controls">
      <%= text_field_tag nil, @vessel_inventory.parts_name, :class => 'number_field', :disabled => true %>
    </div>
  </div>
  <div class="control-group">
    <%= label_tag nil, 'Interval', :class => 'control-label' %>
    <div class="controls">
      <%= text_field_tag nil, [@vessel_inventory.interval_period, @vessel_inventory.interval_period_unit].join(' '), :class => 'number_field', :disabled => true %>
    </div>
  </div>
  <div class="control-group">
    <%= label_tag nil, 'Position', :class => 'control-label' %>
    <div class="controls">
      <%= text_field_tag nil, @vessel_inventory.position, :class => 'number_field', :disabled => true %>
    </div>
  </div>
<!--   <div class="control-group">
    <%#= f.label :location, :class => 'control-label' %>
    <div class="controls">
      <%#= f.text_field :location, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%#= f.label :parts_name, :class => 'control-label' %>
    <div class="controls">
      <%#= f.text_field :parts_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%#= f.label :interval_period, :class => 'control-label' %>
    <div class="controls">
      <%#= f.text_field :interval_period, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%#= f.label :interval_period_unit, :class => 'control-label' %>
    <div class="controls">
      <%#= f.text_field :interval_period_unit, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%#= f.label :position, :class => 'control-label' %>
    <div class="controls">
      <%#= f.text_field :position, :class => 'text_field' %>
    </div>
  </div> -->
  <div class="control-group">
    <%= f.label :last_change_record_period, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_change_record_period, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_change_record_date, :class => 'control-label' %>
    <div class="controls">
      <%#= f.datepicker :last_change_record_date %>
      <div class="input-append date">
        <%= f.text_field :last_change_record_date, :class => 'text_field' %><span class="add-on"><i class="icon-th"></i></span>
      </div>
      <%#= f.text_field :last_change_record_date, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_change_record_executor, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_change_record_executor, :class => 'text_field' %>
    </div>
  </div>

  <% if @vessel_inventory.interval_period_changeable %>
    <div class="control-group">
      <%= f.label :current_hours, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :current_hours, :class => 'number_field' %>
      </div>
    </div>
  <% end %>
<!--  <div class="control-group">
    <%#= f.label :next_change_hours, :class => 'control-label' %>
    <div class="controls">
      <%#= f.text_field :next_change_hours, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%#= f.label :next_change_date, :class => 'control-label' %>
    <div class="controls">
      <%#= f.date_select :next_change_date, :class => 'date_select' %>
    </div>
  </div> -->

  <div class="form-actions">
    <%= f.hidden_field :interval_period_unit %>
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                vessel_inventories_path, :class => 'btn' %>
  </div>
<% end %>

app/views/vessel_inventories/edit.html.erb
<%- model_class = VesselInventory -%>
<div class="page-header">
  <h3><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h3>
</div>
<%= render :partial => 'form' %>

app/views/vessel_inventories/new.html.erb
<%- model_class = VesselInventory -%>
<div class="page-header">
  <h3><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h3>
</div>
<%#= render :partial => 'form' %>
<%#= form_tag(:action => "create", :method => "post") do %>
<%= form_for @vessel_inventory, :html => { :class => 'form-horizontal' } do |f| %>
  <% iteration = 0 %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">BOAT SELECTION</h4>
      </div>
      <div class="panel-body">
        <%= select_tag 'boat_id', options_from_collection_for_select(@tugboats, 'id', 'name'), :prompt => 'Please select a boat' %>
      </div>
    </div>
  <% @values.each do |location, parts_names| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title"><%= location %></h4>
      </div>
      <div class="panel-body">
        <table class='table table-condensed'>
          <thead>
            <tr>
              <th>PARTS NAME</th>
              <th>INTERVAL PERIOD</th>
              <th>INTERVAL PERIOD UNIT</th>
              <%= '<th>NUMBER OF PORT/STBD</th>'.html_safe unless location == 'DECK' %>
            </tr>
          </thead>
          <tbody>
            <% parts_names.each do |part| %>
              <tr>
                <td><%= part %></td>
                <td>
                  <%= hidden_field_tag 'vic['+iteration.to_s+'][location]', location %>
                  <%= hidden_field_tag 'vic['+iteration.to_s+'][parts_name]', part %>
                  <%= text_field_tag 'vic['+iteration.to_s+'][interval_period]', '', :class => 'text_field' %>
                </td>
                <td><%= hours_or_months(iteration, location) %></td>
                <td><%= text_field_tag 'amount['+iteration.to_s+']', '', :class => 'text_field', :value => 1 unless location == 'DECK' %></td>
              </tr>
              <% iteration += 1 %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>

  <div class="form-actions">
    <div class="pull-right">
      <%= submit_tag nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  vessel_inventories_path, :class => 'btn' %>
    </div>
  </div>
<% end %>

app/views/vessel_inventories/show.html.erb
<%- model_class = VesselInventory -%>
<div class="page-header">
  <h3><%=t '.title', :default => model_class.model_name.human.titleize %></h3>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:mdm_tugboat_id) %>:</strong></dt>
  <dd><%= @vessel_inventory.mdm_tugboat_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @vessel_inventory.location %></dd>
  <dt><strong><%= model_class.human_attribute_name(:parts_name) %>:</strong></dt>
  <dd><%= @vessel_inventory.parts_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:interval_period) %>:</strong></dt>
  <dd><%= @vessel_inventory.interval_period %></dd>
  <dt><strong><%= model_class.human_attribute_name(:interval_period_unit) %>:</strong></dt>
  <dd><%= @vessel_inventory.interval_period_unit %></dd>
  <dt><strong><%= model_class.human_attribute_name(:interval_period_changeable) %>:</strong></dt>
  <dd><%= @vessel_inventory.interval_period_changeable %></dd>
  <dt><strong><%= model_class.human_attribute_name(:position) %>:</strong></dt>
  <dd><%= @vessel_inventory.position %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_change_record_period) %>:</strong></dt>
  <dd><%= @vessel_inventory.last_change_record_period %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_change_record_date) %>:</strong></dt>
  <dd><%= @vessel_inventory.last_change_record_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_change_record_executor) %>:</strong></dt>
  <dd><%= @vessel_inventory.last_change_record_executor %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_hours) %>:</strong></dt>
  <dd><%= @vessel_inventory.current_hours %></dd>
  <dt><strong><%= model_class.human_attribute_name(:next_change_hours) %>:</strong></dt>
  <dd><%= @vessel_inventory.next_change_hours %></dd>
  <dt><strong><%= model_class.human_attribute_name(:next_change_date) %>:</strong></dt>
  <dd><%= @vessel_inventory.next_change_date %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              vessel_inventories_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_vessel_inventory_path(@vessel_inventory), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              vessel_inventory_path(@vessel_inventory),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>